CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "ContactInfos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Skype" character varying(100) NULL,
        "Discord" character varying(100) NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_ContactInfos" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "Cellphones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Number" character varying(50) NOT NULL,
        "ContactInfoId" integer NOT NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_Cellphones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cellphones_ContactInfos_ContactInfoId" FOREIGN KEY ("ContactInfoId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "EmailAddresses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Address" character varying(150) NOT NULL,
        "ContactInfoId" integer NOT NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_EmailAddresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmailAddresses_ContactInfos_ContactInfoId" FOREIGN KEY ("ContactInfoId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "Resumes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(150) NOT NULL,
        "YearBirth" integer NOT NULL,
        "Picture" bytea NULL,
        "Description" character varying(3000) NULL,
        "ContactId" integer NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_Resumes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Resumes_ContactInfos_ContactId" FOREIGN KEY ("ContactId") REFERENCES "ContactInfos" ("Id") ON DELETE SET NULL
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "Websites" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Address" character varying(500) NOT NULL,
        "ContactInfoId" integer NOT NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_Websites" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Websites_ContactInfos_ContactInfoId" FOREIGN KEY ("ContactInfoId") REFERENCES "ContactInfos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "Abilities" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Subject" character varying(100) NOT NULL,
        "Experience" character varying(50) NOT NULL,
        "Description" character varying(1000) NULL,
        "Logo" bytea NULL,
        "ResumeId" integer NOT NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_Abilities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Abilities_Resumes_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES "Resumes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "Achievements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(1000) NULL,
        "Year" integer NOT NULL,
        "ResumeId" integer NOT NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_Achievements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Achievements_Resumes_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES "Resumes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "Courses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Institution" character varying(100) NOT NULL,
        "Subject" character varying(100) NOT NULL,
        "YearStart" integer NOT NULL,
        "YearEnd" integer NOT NULL,
        "Description" character varying(1000) NULL,
        "CertificateImage" bytea NULL,
        "CertificateAddress" character varying(500) NULL,
        "Logo" bytea NULL,
        "InstitutionWebsite" character varying(150) NULL,
        "ResumeId" integer NOT NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_Courses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Courses_Resumes_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES "Resumes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "Experiences" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Company" character varying(150) NOT NULL,
        "Field" character varying(100) NULL,
        "Role" character varying(120) NOT NULL,
        "YearStart" integer NOT NULL,
        "YearEnd" integer NULL,
        "Notes" character varying(1000) NULL,
        "CompanyWebsite" character varying(150) NULL,
        "ResumeId" integer NOT NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_Experiences" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Experiences_Resumes_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES "Resumes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE TABLE "Goals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MyGoal" character varying(500) NOT NULL,
        "ResumeId" integer NOT NULL,
        "LastUpdate" timestamp NOT NULL DEFAULT (current_timestamp),
        CONSTRAINT "PK_Goals" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Goals_Resumes_ResumeId" FOREIGN KEY ("ResumeId") REFERENCES "Resumes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE INDEX "IX_Abilities_ResumeId" ON "Abilities" ("ResumeId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE INDEX "IX_Achievements_ResumeId" ON "Achievements" ("ResumeId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE INDEX "IX_Cellphones_ContactInfoId" ON "Cellphones" ("ContactInfoId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE INDEX "IX_Courses_ResumeId" ON "Courses" ("ResumeId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE INDEX "IX_EmailAddresses_ContactInfoId" ON "EmailAddresses" ("ContactInfoId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE INDEX "IX_Experiences_ResumeId" ON "Experiences" ("ResumeId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE INDEX "IX_Goals_ResumeId" ON "Goals" ("ResumeId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE INDEX "IX_Resumes_ContactId" ON "Resumes" ("ContactId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    CREATE INDEX "IX_Websites_ContactInfoId" ON "Websites" ("ContactInfoId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210829163306_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210829163306_Initial', '5.0.7');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210830233354_ResumeLanguageSupport') THEN
    ALTER TABLE "Resumes" ADD "Language" character varying(100) NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210830233354_ResumeLanguageSupport') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210830233354_ResumeLanguageSupport', '5.0.7');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210831201635_OrderItems') THEN
    ALTER TABLE "Goals" ADD "Order" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210831201635_OrderItems') THEN
    ALTER TABLE "Experiences" ADD "Order" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210831201635_OrderItems') THEN
    ALTER TABLE "Courses" ADD "Order" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210831201635_OrderItems') THEN
    ALTER TABLE "Achievements" ADD "Order" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210831201635_OrderItems') THEN
    ALTER TABLE "Abilities" ADD "Order" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210831201635_OrderItems') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210831201635_OrderItems', '5.0.7');
    END IF;
END $$;
COMMIT;

